# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'hashCode' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for hashCode
 
  pod 'Firebase/Core'
  pod 'Firebase/Auth'  
  pod 'Firebase/Firestore'

  target 'hashCodeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'hashCode-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for hashCode-tvOS

  target 'hashCode-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
